# Generated by Django 4.2 on 2023-04-04 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('number_of_seats', models.IntegerField(default=50)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
